// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyItems.Backend;

#nullable disable

namespace MyItems.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230704101154_UsersAndItem")]
    partial class UsersAndItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyItems.Backend.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MyItems.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b7c7089-0efc-4be2-85f7-6c19f40ce596"),
                            Email = "Clarence_Bogan@hotmail.com",
                            FirstName = "Clarence",
                            IsAdmin = false,
                            LastName = "Bogan",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("d2337e58-e445-4dfc-96bf-c88814f06468"),
                            Email = "Clarence96@hotmail.com",
                            FirstName = "Clarence",
                            IsAdmin = false,
                            LastName = "Rempel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("6b1359de-5155-4f30-bb73-2400f1ce4d03"),
                            Email = "Isaac.King@gmail.com",
                            FirstName = "Isaac",
                            IsAdmin = false,
                            LastName = "King",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("abfa4bd0-2986-43bf-b86b-e69a9cf082bb"),
                            Email = "Stephanie.OKeefe@hotmail.com",
                            FirstName = "Stephanie",
                            IsAdmin = false,
                            LastName = "O'Keefe",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("20e606ee-dec5-4d6a-868f-b06b8a60b537"),
                            Email = "Ruth_Boyer@yahoo.com",
                            FirstName = "Ruth",
                            IsAdmin = false,
                            LastName = "Boyer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7f52b58c-4d3a-4063-a301-bd9642e5d11d"),
                            Email = "Fernando60@yahoo.com",
                            FirstName = "Fernando",
                            IsAdmin = false,
                            LastName = "Simonis",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("c40db953-0063-4310-ac45-242fd51c9007"),
                            Email = "Barry.Moen@hotmail.com",
                            FirstName = "Barry",
                            IsAdmin = false,
                            LastName = "Moen",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("014f93e1-24a0-4771-91b2-03e14d08bce7"),
                            Email = "Lisa58@gmail.com",
                            FirstName = "Lisa",
                            IsAdmin = false,
                            LastName = "Cormier",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1b6f00bd-2384-4909-9136-699aca0c8c9b"),
                            Email = "Gretchen.Bartell@yahoo.com",
                            FirstName = "Gretchen",
                            IsAdmin = false,
                            LastName = "Bartell",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2ae6c847-18b5-4f62-8a34-5d3b31950115"),
                            Email = "Marie.Koch99@gmail.com",
                            FirstName = "Marie",
                            IsAdmin = false,
                            LastName = "Koch",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e740fc39-369d-42dd-9846-ae91f124014f"),
                            Email = "Colleen21@gmail.com",
                            FirstName = "Colleen",
                            IsAdmin = false,
                            LastName = "Bergstrom",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("3879ee5f-3169-4655-bf2f-0ffd8324678a"),
                            Email = "Mary_Feest78@hotmail.com",
                            FirstName = "Mary",
                            IsAdmin = false,
                            LastName = "Feest",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("38fb925b-4057-44fb-9460-61b6ca6351d9"),
                            Email = "Julius68@hotmail.com",
                            FirstName = "Julius",
                            IsAdmin = false,
                            LastName = "Sanford",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("3b43581c-9a8e-4cba-9c06-f37650e88cb5"),
                            Email = "Amanda32@yahoo.com",
                            FirstName = "Amanda",
                            IsAdmin = false,
                            LastName = "Fadel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("30a075c6-7226-4534-b99e-38d2a61cf948"),
                            Email = "Tony.Harvey55@yahoo.com",
                            FirstName = "Tony",
                            IsAdmin = false,
                            LastName = "Harvey",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("46f0c949-e55e-452e-a04e-b44a374d8279"),
                            Email = "Chad_Kuphal@gmail.com",
                            FirstName = "Chad",
                            IsAdmin = false,
                            LastName = "Kuphal",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("025ef259-0368-4643-9d98-f78a5fd79123"),
                            Email = "Beatrice.Gislason@gmail.com",
                            FirstName = "Beatrice",
                            IsAdmin = false,
                            LastName = "Gislason",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7e2eaf91-aa94-4e7c-80aa-1df2c70dcb04"),
                            Email = "Rolando_Medhurst51@hotmail.com",
                            FirstName = "Rolando",
                            IsAdmin = false,
                            LastName = "Medhurst",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("4342973b-ee5b-4e6c-942c-eeb2ef3f8958"),
                            Email = "Angel74@gmail.com",
                            FirstName = "Angel",
                            IsAdmin = false,
                            LastName = "Funk",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("bde60a12-6366-43b5-8a19-fac52cc90056"),
                            Email = "Kari52@hotmail.com",
                            FirstName = "Kari",
                            IsAdmin = false,
                            LastName = "Murazik",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a80b2a2a-384e-44ba-9ce9-a1393510f7ac"),
                            Email = "Alfonso_Satterfield33@yahoo.com",
                            FirstName = "Alfonso",
                            IsAdmin = false,
                            LastName = "Satterfield",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("41394ef8-2cd2-44ad-a532-1f254a19ee86"),
                            Email = "Lori.Bergnaum@gmail.com",
                            FirstName = "Lori",
                            IsAdmin = false,
                            LastName = "Bergnaum",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("be891714-6fc4-4548-b123-c165b22a0eb1"),
                            Email = "Kathy_Jones51@gmail.com",
                            FirstName = "Kathy",
                            IsAdmin = false,
                            LastName = "Jones",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("96db09c8-2f24-41d1-8f7c-44a90841c9c9"),
                            Email = "Melanie.Kunde@yahoo.com",
                            FirstName = "Melanie",
                            IsAdmin = false,
                            LastName = "Kunde",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5aa9c965-5dc2-40e5-9f63-97812c4df218"),
                            Email = "Ellis.Lockman@hotmail.com",
                            FirstName = "Ellis",
                            IsAdmin = false,
                            LastName = "Lockman",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("d75319f7-5017-48b6-9d30-43be7050d1f7"),
                            Email = "Edwin49@yahoo.com",
                            FirstName = "Edwin",
                            IsAdmin = false,
                            LastName = "Thompson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("02b660ba-8f01-443a-935d-000b6a793285"),
                            Email = "Lucille.Langosh5@yahoo.com",
                            FirstName = "Lucille",
                            IsAdmin = false,
                            LastName = "Langosh",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8fa387dd-17b8-4254-a840-f9a383d600ad"),
                            Email = "Kate95@yahoo.com",
                            FirstName = "Kate",
                            IsAdmin = false,
                            LastName = "Halvorson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("005ad8a6-d1f5-48e0-83c0-7ec37edfa8ea"),
                            Email = "Marsha.Larkin@gmail.com",
                            FirstName = "Marsha",
                            IsAdmin = false,
                            LastName = "Larkin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b5973ea0-9c6c-46ab-ac59-fa2f47390513"),
                            Email = "Ray_Bernhard@yahoo.com",
                            FirstName = "Ray",
                            IsAdmin = false,
                            LastName = "Bernhard",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("d102f04b-c648-46c6-a2eb-0c29420dc242"),
                            Email = "Stacey.Heller11@hotmail.com",
                            FirstName = "Stacey",
                            IsAdmin = false,
                            LastName = "Heller",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("98de820e-5bcd-4edf-a072-d9dfa25d1e7f"),
                            Email = "Adrienne.Kiehn1@yahoo.com",
                            FirstName = "Adrienne",
                            IsAdmin = false,
                            LastName = "Kiehn",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("0a92702e-d715-4ed0-a785-cdf7e45d3c6e"),
                            Email = "Shawn_Schmeler@hotmail.com",
                            FirstName = "Shawn",
                            IsAdmin = false,
                            LastName = "Schmeler",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7f3fee62-0670-48d8-9851-781e02b7667d"),
                            Email = "Corey.Kemmer77@yahoo.com",
                            FirstName = "Corey",
                            IsAdmin = false,
                            LastName = "Kemmer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("ab707a80-1aeb-4241-af8e-e199cc627220"),
                            Email = "Stewart.Mertz77@gmail.com",
                            FirstName = "Stewart",
                            IsAdmin = false,
                            LastName = "Mertz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f571f135-193c-4a13-81bc-28698833f4d1"),
                            Email = "Tyrone_Huel@gmail.com",
                            FirstName = "Tyrone",
                            IsAdmin = false,
                            LastName = "Huel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("808be1b0-5d0a-4060-8702-4fa7878ab121"),
                            Email = "Tanya.Collier@yahoo.com",
                            FirstName = "Tanya",
                            IsAdmin = false,
                            LastName = "Collier",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("fafa0261-0cf9-48bd-9bb7-14b70715b70f"),
                            Email = "Mindy.Pfeffer@gmail.com",
                            FirstName = "Mindy",
                            IsAdmin = false,
                            LastName = "Pfeffer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b5b51c3e-6122-4728-b3fb-a82de7190c76"),
                            Email = "Matthew.Cronin67@yahoo.com",
                            FirstName = "Matthew",
                            IsAdmin = false,
                            LastName = "Cronin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("c090bb74-e8ef-41f2-be19-512dc1a6a666"),
                            Email = "Paula32@gmail.com",
                            FirstName = "Paula",
                            IsAdmin = false,
                            LastName = "Torp",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("c946b0b1-91df-423b-b374-bf1f6640b441"),
                            Email = "Jean.Fritsch77@hotmail.com",
                            FirstName = "Jean",
                            IsAdmin = false,
                            LastName = "Fritsch",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("4cdc370a-5c9a-447e-b7aa-61406cc9e1a1"),
                            Email = "Hugo_OReilly@hotmail.com",
                            FirstName = "Hugo",
                            IsAdmin = false,
                            LastName = "O'Reilly",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b4a84ee8-5c76-4338-bfed-2aaebfea6648"),
                            Email = "Ross.Steuber@yahoo.com",
                            FirstName = "Ross",
                            IsAdmin = false,
                            LastName = "Steuber",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8154be14-b256-4fd8-af90-ccce5db6a81c"),
                            Email = "Raymond41@hotmail.com",
                            FirstName = "Raymond",
                            IsAdmin = false,
                            LastName = "Gerlach",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8d9b98df-3394-4e59-a76b-f04869286f96"),
                            Email = "Grady28@yahoo.com",
                            FirstName = "Grady",
                            IsAdmin = false,
                            LastName = "Turner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("ffc5cf32-0ac0-4335-b027-da65c048763c"),
                            Email = "Laura.Ebert80@hotmail.com",
                            FirstName = "Laura",
                            IsAdmin = false,
                            LastName = "Ebert",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("47a7428c-9b35-460c-8e25-62d3be9147ab"),
                            Email = "Lawrence45@gmail.com",
                            FirstName = "Lawrence",
                            IsAdmin = false,
                            LastName = "Ortiz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b26d4843-0d6c-4b80-9fb8-4f3ab8a23433"),
                            Email = "Herbert.Kunde@yahoo.com",
                            FirstName = "Herbert",
                            IsAdmin = false,
                            LastName = "Kunde",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("111c7561-d2ce-4cf1-8b34-e282853ab7d4"),
                            Email = "Orlando.Kessler68@gmail.com",
                            FirstName = "Orlando",
                            IsAdmin = false,
                            LastName = "Kessler",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5bf3ca5e-a23d-42bc-be6f-167a0b6b0448"),
                            Email = "Myra_Brekke@yahoo.com",
                            FirstName = "Myra",
                            IsAdmin = false,
                            LastName = "Brekke",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("de7b6e24-dd13-4be0-a5a7-8c640feacd67"),
                            Email = "Eric_Ebert@hotmail.com",
                            FirstName = "Eric",
                            IsAdmin = false,
                            LastName = "Ebert",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("64ad73e7-4756-48aa-af3e-c501d2a0559c"),
                            Email = "Emmett_Cronin10@gmail.com",
                            FirstName = "Emmett",
                            IsAdmin = false,
                            LastName = "Cronin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("55eb161a-44d2-46c2-8d37-d34b3e402e75"),
                            Email = "Lewis.Yost@yahoo.com",
                            FirstName = "Lewis",
                            IsAdmin = false,
                            LastName = "Yost",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a64590cc-7014-4b6c-95c8-81797308a9fe"),
                            Email = "Leona_Graham@gmail.com",
                            FirstName = "Leona",
                            IsAdmin = false,
                            LastName = "Graham",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("0a64c8ec-ba89-4b31-9796-191726bd8b71"),
                            Email = "Olivia.Mertz9@yahoo.com",
                            FirstName = "Olivia",
                            IsAdmin = false,
                            LastName = "Mertz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7c9464bd-303c-4477-9f2f-b62e78ac290d"),
                            Email = "Garrett_Renner3@hotmail.com",
                            FirstName = "Garrett",
                            IsAdmin = false,
                            LastName = "Renner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2a50c99b-2e0a-4934-977a-191191f7d1e8"),
                            Email = "Mike55@gmail.com",
                            FirstName = "Mike",
                            IsAdmin = false,
                            LastName = "Ernser",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("eafce636-a867-40ff-a234-9b3a8709a4d9"),
                            Email = "Sergio_Fay@gmail.com",
                            FirstName = "Sergio",
                            IsAdmin = false,
                            LastName = "Fay",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("fc477cef-8030-4330-8057-20cef31571ee"),
                            Email = "Winston.Schmidt@hotmail.com",
                            FirstName = "Winston",
                            IsAdmin = false,
                            LastName = "Schmidt",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("25d4b419-8796-4805-b92c-5b5ac7de71dd"),
                            Email = "Laura.Jacobi97@hotmail.com",
                            FirstName = "Laura",
                            IsAdmin = false,
                            LastName = "Jacobi",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("d675faba-c3b9-4db3-a1d5-88bdf146390f"),
                            Email = "Chester_Sawayn5@gmail.com",
                            FirstName = "Chester",
                            IsAdmin = false,
                            LastName = "Sawayn",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("fd2a573e-4ec3-40c6-ac52-8e744f39fbc6"),
                            Email = "Kellie.Huel@yahoo.com",
                            FirstName = "Kellie",
                            IsAdmin = false,
                            LastName = "Huel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f52bcc59-493d-4a65-901c-085bf705c555"),
                            Email = "Gary.Haag@gmail.com",
                            FirstName = "Gary",
                            IsAdmin = false,
                            LastName = "Haag",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("00ca218e-73a2-4a93-9cad-a0160f6ca0dd"),
                            Email = "Hazel69@yahoo.com",
                            FirstName = "Hazel",
                            IsAdmin = false,
                            LastName = "Gulgowski",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("837fe6c9-8f2b-46d8-ac77-e0c03932d5fc"),
                            Email = "Lee50@gmail.com",
                            FirstName = "Lee",
                            IsAdmin = false,
                            LastName = "Block",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7fdaa8e4-5188-4e70-bd11-440b9c61767f"),
                            Email = "Kelly37@gmail.com",
                            FirstName = "Kelly",
                            IsAdmin = false,
                            LastName = "Hermann",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("aefdbc1a-df12-44fc-afe9-435d706efbff"),
                            Email = "Ruby.Ferry@gmail.com",
                            FirstName = "Ruby",
                            IsAdmin = false,
                            LastName = "Ferry",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b8acf611-188f-4bd0-b306-40ae0bbf2ea6"),
                            Email = "Eugene_Heller13@yahoo.com",
                            FirstName = "Eugene",
                            IsAdmin = false,
                            LastName = "Heller",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("133883a7-2a84-4fd7-95b6-041a4dc18d6b"),
                            Email = "Winifred.Lakin@gmail.com",
                            FirstName = "Winifred",
                            IsAdmin = false,
                            LastName = "Lakin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("05131e99-aaa8-4bd1-9bae-c93224e581f7"),
                            Email = "Myra58@hotmail.com",
                            FirstName = "Myra",
                            IsAdmin = false,
                            LastName = "Kertzmann",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("14ca4e81-c5f9-444e-b760-53b31b4f7c86"),
                            Email = "Elvira53@yahoo.com",
                            FirstName = "Elvira",
                            IsAdmin = false,
                            LastName = "Pagac",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("acf79066-bf70-49c2-8309-af7886309349"),
                            Email = "Jenna_Hegmann@yahoo.com",
                            FirstName = "Jenna",
                            IsAdmin = false,
                            LastName = "Hegmann",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("cd357cf6-80c9-4049-aca6-6a678e7d77be"),
                            Email = "Pablo.Halvorson@hotmail.com",
                            FirstName = "Pablo",
                            IsAdmin = false,
                            LastName = "Halvorson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("eb9a35f6-7385-4b95-9c57-18be76a43811"),
                            Email = "Marjorie96@gmail.com",
                            FirstName = "Marjorie",
                            IsAdmin = false,
                            LastName = "Schmidt",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b8ab0329-4cdf-4407-96fd-8d688a5d2035"),
                            Email = "Alyssa.Schiller17@yahoo.com",
                            FirstName = "Alyssa",
                            IsAdmin = false,
                            LastName = "Schiller",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("c9a059b7-1665-4855-8265-9cce3eef77de"),
                            Email = "Leslie64@yahoo.com",
                            FirstName = "Leslie",
                            IsAdmin = false,
                            LastName = "Willms",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("29dcffc2-8a7c-4acc-b9f5-1c9107774e38"),
                            Email = "Jack.Fadel38@hotmail.com",
                            FirstName = "Jack",
                            IsAdmin = false,
                            LastName = "Fadel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("cd2bd3f9-3632-49a4-be06-85ddd95ca2b4"),
                            Email = "Julie.Pacocha99@yahoo.com",
                            FirstName = "Julie",
                            IsAdmin = false,
                            LastName = "Pacocha",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("91bd6b32-654f-400f-923a-0caf76a0d0a4"),
                            Email = "Lynne2@gmail.com",
                            FirstName = "Lynne",
                            IsAdmin = false,
                            LastName = "Orn",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2ce8a8ce-b76e-49c7-9611-58b5fb060a4c"),
                            Email = "Pedro27@yahoo.com",
                            FirstName = "Pedro",
                            IsAdmin = false,
                            LastName = "Schmidt",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b9c37284-884c-4835-8535-6b0c9308a3f3"),
                            Email = "Alton29@hotmail.com",
                            FirstName = "Alton",
                            IsAdmin = false,
                            LastName = "Bartell",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2a77e367-ae20-4693-9893-538385400a83"),
                            Email = "Josh30@yahoo.com",
                            FirstName = "Josh",
                            IsAdmin = false,
                            LastName = "Hodkiewicz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8ea302c0-7fc0-46dc-86b5-005c38d0362f"),
                            Email = "Lionel.Konopelski@hotmail.com",
                            FirstName = "Lionel",
                            IsAdmin = false,
                            LastName = "Konopelski",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("34d2659b-0b69-4187-92c1-cbe800b827af"),
                            Email = "Jana_Murphy10@yahoo.com",
                            FirstName = "Jana",
                            IsAdmin = false,
                            LastName = "Murphy",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("35bb932c-bb9e-4f95-85e8-138d95218b24"),
                            Email = "Patty.Tillman@yahoo.com",
                            FirstName = "Patty",
                            IsAdmin = false,
                            LastName = "Tillman",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e5ea9271-19b0-47f9-917e-47d7dfffb778"),
                            Email = "Marianne43@hotmail.com",
                            FirstName = "Marianne",
                            IsAdmin = false,
                            LastName = "Hand",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("51116616-2679-434c-8217-6c821576d73d"),
                            Email = "Bernadette79@gmail.com",
                            FirstName = "Bernadette",
                            IsAdmin = false,
                            LastName = "Medhurst",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("20a4b67e-3d40-4b1e-94ca-152c84003f59"),
                            Email = "Ed.Goldner50@yahoo.com",
                            FirstName = "Ed",
                            IsAdmin = false,
                            LastName = "Goldner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f38cfe9c-38f2-44b2-b48c-bfc1e48d42da"),
                            Email = "Jean.Ledner@yahoo.com",
                            FirstName = "Jean",
                            IsAdmin = false,
                            LastName = "Ledner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a0964213-378f-4a3d-8974-53fd886c2164"),
                            Email = "Gayle2@gmail.com",
                            FirstName = "Gayle",
                            IsAdmin = false,
                            LastName = "Mayer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5f279b36-9a31-41f9-a9a0-1fe1a3b637c9"),
                            Email = "Wendy2@hotmail.com",
                            FirstName = "Wendy",
                            IsAdmin = false,
                            LastName = "Gaylord",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7bd52d86-49c5-4522-a2fa-3f7612f1f73a"),
                            Email = "Carla.West3@hotmail.com",
                            FirstName = "Carla",
                            IsAdmin = false,
                            LastName = "West",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f48dac65-142e-4664-a6f8-d7159f0d03c0"),
                            Email = "Clifton.Keebler@hotmail.com",
                            FirstName = "Clifton",
                            IsAdmin = false,
                            LastName = "Keebler",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("358180c2-0500-412d-bd5d-24289827a7a4"),
                            Email = "Sidney.Auer@hotmail.com",
                            FirstName = "Sidney",
                            IsAdmin = false,
                            LastName = "Auer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a902f723-9ded-4e0a-8738-dbcddcd7b0b1"),
                            Email = "Tara_Rogahn@yahoo.com",
                            FirstName = "Tara",
                            IsAdmin = false,
                            LastName = "Rogahn",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("0cefaed9-cb19-4833-a953-f87a0d41dfce"),
                            Email = "Anthony12@gmail.com",
                            FirstName = "Anthony",
                            IsAdmin = false,
                            LastName = "Schneider",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2f4d569a-37fb-4594-a9a5-767983ceec8d"),
                            Email = "Roxanne.Macejkovic@yahoo.com",
                            FirstName = "Roxanne",
                            IsAdmin = false,
                            LastName = "Macejkovic",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("089e6d5c-ec8c-472a-b0ba-fedcdeec67b8"),
                            Email = "Monica.Thompson64@hotmail.com",
                            FirstName = "Monica",
                            IsAdmin = false,
                            LastName = "Thompson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("80279985-6615-4b70-a57b-9f789ae279d4"),
                            Email = "Wade_Macejkovic55@hotmail.com",
                            FirstName = "Wade",
                            IsAdmin = false,
                            LastName = "Macejkovic",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("085faca8-e4aa-4e18-9329-ae4b0e9a302f"),
                            Email = "Kristine67@gmail.com",
                            FirstName = "Kristine",
                            IsAdmin = false,
                            LastName = "Beatty",
                            PasswordHash = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
