// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyItems.Backend;

#nullable disable

namespace MyItems.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyItems.Backend.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MyItems.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb6b5a43-2089-4dd3-9162-3972535a6e78"),
                            Email = "Sabrina.Sauer70@gmail.com",
                            FirstName = "Sabrina",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Sauer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("943366cc-a054-48ce-a502-8bac0bebaeba"),
                            Email = "Kristi_Lakin56@hotmail.com",
                            FirstName = "Kristi",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lakin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("142742ea-8e43-4f98-a9c5-37c4f43d0998"),
                            Email = "Cecilia_DAmore98@hotmail.com",
                            FirstName = "Cecilia",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "D'Amore",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b42c34bc-0df1-4599-a860-955673bdaeac"),
                            Email = "Armando6@hotmail.com",
                            FirstName = "Armando",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Prosacco",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8121995e-e655-47c5-ab16-e599c335b550"),
                            Email = "Anne_Larson56@yahoo.com",
                            FirstName = "Anne",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Larson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("192cd36f-7619-4053-a2ba-c04d95ab9a57"),
                            Email = "Regina_Leffler19@gmail.com",
                            FirstName = "Regina",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Leffler",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1dc807df-6647-4b9d-96f2-d58e1b4d28b5"),
                            Email = "Kate_Cummerata36@gmail.com",
                            FirstName = "Kate",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Cummerata",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("047bff45-db44-4c3f-ba7c-0c1366777e95"),
                            Email = "Kellie_Gulgowski@gmail.com",
                            FirstName = "Kellie",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Gulgowski",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("cda83869-ebb9-4029-94b8-bdf2e59cbb93"),
                            Email = "Guadalupe11@yahoo.com",
                            FirstName = "Guadalupe",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Daniel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e330027b-ee1c-4881-aef8-df4433955f11"),
                            Email = "Dexter29@gmail.com",
                            FirstName = "Dexter",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "McClure",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8a86d73d-580e-4977-bcac-cad1293ca35d"),
                            Email = "Hattie93@gmail.com",
                            FirstName = "Hattie",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Homenick",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2a31c583-0d04-40b5-aae4-3767b1585894"),
                            Email = "Kayla75@yahoo.com",
                            FirstName = "Kayla",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Cummings",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1f959bd9-70d3-4e4b-a0ff-2fd7859841a0"),
                            Email = "Rudolph.Feest5@hotmail.com",
                            FirstName = "Rudolph",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Feest",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b9062285-a10d-4020-8a97-ca0ade198370"),
                            Email = "Ellis.Brakus@yahoo.com",
                            FirstName = "Ellis",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Brakus",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("3b44946f-fa22-4d50-ab67-aad3584023f4"),
                            Email = "Clay.Jakubowski@hotmail.com",
                            FirstName = "Clay",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Jakubowski",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("586cd5c9-48c7-4197-8435-e86efb57e84f"),
                            Email = "Doyle_Gleason@yahoo.com",
                            FirstName = "Doyle",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Gleason",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("aaac5a74-7c78-447e-9916-23a883de7d17"),
                            Email = "Randy.Hansen11@yahoo.com",
                            FirstName = "Randy",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Hansen",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5d874d8f-d58f-44ad-b189-d44a72fe58e2"),
                            Email = "Paul21@gmail.com",
                            FirstName = "Paul",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Jacobi",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("17c50a68-14ba-4873-a23e-09b4c5a8eeb0"),
                            Email = "Heidi68@yahoo.com",
                            FirstName = "Heidi",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Bednar",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("c92a1743-1c3f-43e3-9119-69afdb049b07"),
                            Email = "Terrence_Kautzer@gmail.com",
                            FirstName = "Terrence",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Kautzer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7b5ae499-aabe-4a3f-a328-9b251e5acd35"),
                            Email = "Alton.Rolfson61@hotmail.com",
                            FirstName = "Alton",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Rolfson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1b72daf3-c0cc-4f2c-ac73-f4884157cfb0"),
                            Email = "Randall_Schinner80@gmail.com",
                            FirstName = "Randall",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Schinner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("20e18e6a-5b1d-4d65-a777-7ef20c97b334"),
                            Email = "Gwen21@gmail.com",
                            FirstName = "Gwen",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Cremin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("9f591fd5-7dab-49f0-8140-b9039fdedf21"),
                            Email = "Elisa_DAmore@hotmail.com",
                            FirstName = "Elisa",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "D'Amore",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1c1b6730-16a9-49d7-8e31-21916a554028"),
                            Email = "Ronnie10@hotmail.com",
                            FirstName = "Ronnie",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Grant",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a8683f6a-e92f-47a6-8dee-f74ccd60705f"),
                            Email = "Tom74@yahoo.com",
                            FirstName = "Tom",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Botsford",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2779f43c-9a5b-42c2-a69c-532ff3c81c01"),
                            Email = "Dustin.Morissette10@yahoo.com",
                            FirstName = "Dustin",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Morissette",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("af70de84-f0a0-4e2a-9972-3ba5446a3c64"),
                            Email = "Timmy_Thompson42@gmail.com",
                            FirstName = "Timmy",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Thompson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e0af0f62-ab96-4df6-8156-8f9745232b7e"),
                            Email = "Micheal_Armstrong@yahoo.com",
                            FirstName = "Micheal",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Armstrong",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e4909eb7-1437-46cf-a389-8f4ae1d98756"),
                            Email = "Clara.Murazik46@gmail.com",
                            FirstName = "Clara",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Murazik",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8fffc615-a434-4026-8490-94bd2d2046a5"),
                            Email = "Doris_Quigley96@yahoo.com",
                            FirstName = "Doris",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Quigley",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("8252d18e-b019-4746-8568-bf5fc722293b"),
                            Email = "Delia_Nolan@yahoo.com",
                            FirstName = "Delia",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Nolan",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("366cb5d4-f81d-4b2d-89ff-07c2449c4a11"),
                            Email = "Vicki.Graham24@hotmail.com",
                            FirstName = "Vicki",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Graham",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b788a4bb-9daa-44d6-afe1-4ba5d514d338"),
                            Email = "Luz.McKenzie@hotmail.com",
                            FirstName = "Luz",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "McKenzie",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("84768966-c40f-4882-a7ac-d42d5551ce2e"),
                            Email = "Krista.Homenick@yahoo.com",
                            FirstName = "Krista",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Homenick",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f9d58852-1a10-485d-a8d2-07a714cfe3b1"),
                            Email = "Lela_Flatley5@hotmail.com",
                            FirstName = "Lela",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Flatley",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("4c871c3a-84a9-4c34-99b2-6f91b54b0623"),
                            Email = "Bert47@hotmail.com",
                            FirstName = "Bert",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Effertz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("c7160950-1876-4548-9f15-804a52c07eca"),
                            Email = "Terry21@gmail.com",
                            FirstName = "Terry",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Zieme",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5c7615ef-7bf3-4f19-8bd9-135c3e81d9cb"),
                            Email = "Sylvester.Renner@hotmail.com",
                            FirstName = "Sylvester",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Renner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("460373a0-ffd5-480f-bea8-f508d01c797b"),
                            Email = "Kathleen.Effertz@hotmail.com",
                            FirstName = "Kathleen",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Effertz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("fb7101a5-65ad-4913-adcf-414c170cf413"),
                            Email = "Stewart_Kub@gmail.com",
                            FirstName = "Stewart",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Kub",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("0d20cae1-5793-4924-9ac6-5613665f8646"),
                            Email = "Tricia_Koepp@hotmail.com",
                            FirstName = "Tricia",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Koepp",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("0fe92d36-e22f-4646-bf5d-78cd2c36bff6"),
                            Email = "Victoria19@gmail.com",
                            FirstName = "Victoria",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Kessler",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2be983c3-d035-4ccd-9376-d3be97da2907"),
                            Email = "Arturo.McLaughlin@yahoo.com",
                            FirstName = "Arturo",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "McLaughlin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b2421df9-c196-47c1-a14f-4bfcd6747f77"),
                            Email = "Penny66@hotmail.com",
                            FirstName = "Penny",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Gaylord",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("dc7aa436-d8a0-4fc4-b2ef-caff156be4d0"),
                            Email = "Clara_Littel27@hotmail.com",
                            FirstName = "Clara",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Littel",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("803ec5b6-3d2d-40e0-ab73-56e01fc96398"),
                            Email = "Ernesto14@hotmail.com",
                            FirstName = "Ernesto",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lindgren",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f8611ac8-1d33-4437-9abd-6bceeb3e4829"),
                            Email = "Eugene_Bechtelar@yahoo.com",
                            FirstName = "Eugene",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Bechtelar",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("0ff0cb3d-db81-460f-b95b-27317d688213"),
                            Email = "Marion_Jast20@yahoo.com",
                            FirstName = "Marion",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Jast",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("d66c2daf-6d4c-49b7-8582-d7f74d930bb1"),
                            Email = "Salvador36@gmail.com",
                            FirstName = "Salvador",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Leffler",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("969d5af2-6859-442f-8d7b-ea33d3a37738"),
                            Email = "Alejandro.Mills68@yahoo.com",
                            FirstName = "Alejandro",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Mills",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b88df6ec-7e60-42f7-989a-b90be4005c47"),
                            Email = "Leticia42@yahoo.com",
                            FirstName = "Leticia",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lebsack",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b8d1ee30-ed76-4c0d-9c55-6a42622f3b69"),
                            Email = "Geneva0@hotmail.com",
                            FirstName = "Geneva",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Kuhlman",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("88cc41c5-7e99-4680-84cc-c47f95c8b6b5"),
                            Email = "Sammy_Mohr@yahoo.com",
                            FirstName = "Sammy",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Mohr",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("cbea21fd-4441-479b-adad-f0df50b9fda7"),
                            Email = "Sonja.Tremblay@hotmail.com",
                            FirstName = "Sonja",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Tremblay",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("12adb40b-f914-42d9-b64e-a899c08a452e"),
                            Email = "Daniel.OConner31@hotmail.com",
                            FirstName = "Daniel",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "O'Conner",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("6fd7e1d0-f33b-44c6-bed9-1818f7d5adcc"),
                            Email = "Allison31@hotmail.com",
                            FirstName = "Allison",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Sipes",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b0c1c7db-2a6d-4109-8618-8e90a80a8adc"),
                            Email = "Elisa_Torphy@hotmail.com",
                            FirstName = "Elisa",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Torphy",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f1e6ea5b-7208-4370-a43e-bc31652bfda1"),
                            Email = "Veronica79@yahoo.com",
                            FirstName = "Veronica",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Denesik",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("7b09458f-0544-431f-950f-b6e804dcf1f1"),
                            Email = "Salvador.Schultz@yahoo.com",
                            FirstName = "Salvador",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Schultz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("02a89536-3b2f-4291-b1b2-16628e723a1b"),
                            Email = "Bryan_Reichert@hotmail.com",
                            FirstName = "Bryan",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Reichert",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("ee47f559-530c-4877-9ba7-a2e5ac73d38f"),
                            Email = "Keith_Balistreri5@yahoo.com",
                            FirstName = "Keith",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Balistreri",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b04ada0a-7c87-4984-b8b8-a1446e13c876"),
                            Email = "Ted16@hotmail.com",
                            FirstName = "Ted",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Nienow",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("748ff02d-8569-4d85-9c04-46604f2a1ccb"),
                            Email = "Darrell35@hotmail.com",
                            FirstName = "Darrell",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Rohan",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("f7935695-1362-42f1-9741-6a8f5ccc394b"),
                            Email = "Steven33@hotmail.com",
                            FirstName = "Steven",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Mertz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("92db914f-75cb-4dde-92de-3f2ac840beb7"),
                            Email = "Danny55@hotmail.com",
                            FirstName = "Danny",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Cartwright",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e698084d-0eba-497b-b5b4-eaa4cf7b9323"),
                            Email = "Sonja_Effertz8@gmail.com",
                            FirstName = "Sonja",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Effertz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1e01d217-628b-4292-b17f-d97156d201a7"),
                            Email = "Mae_Morissette@gmail.com",
                            FirstName = "Mae",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Morissette",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("93c2d8c0-0ff3-4f3c-95a2-affd057b7f35"),
                            Email = "Omar.Hermiston72@yahoo.com",
                            FirstName = "Omar",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Hermiston",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b8386c64-85ed-448c-8e7c-63b6e4a62560"),
                            Email = "Dave_Cronin3@gmail.com",
                            FirstName = "Dave",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Cronin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("fefbfcff-45d9-4c5c-850f-21c1ba6013ae"),
                            Email = "Rene94@gmail.com",
                            FirstName = "Rene",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Wintheiser",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("09a5731d-50a8-4a65-8ee5-1afa4e2271cd"),
                            Email = "Bobbie_Hackett@yahoo.com",
                            FirstName = "Bobbie",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Hackett",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("2ebc9ca1-b892-406a-8246-96d90c9c92b5"),
                            Email = "Johnathan.Steuber63@yahoo.com",
                            FirstName = "Johnathan",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Steuber",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("292c9e4d-2faf-4039-9240-a68502089041"),
                            Email = "Richard_Okuneva@hotmail.com",
                            FirstName = "Richard",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Okuneva",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("964d8000-0797-4420-8dd3-65667e0935fc"),
                            Email = "Darla75@hotmail.com",
                            FirstName = "Darla",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Simonis",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("01739e95-1cf0-4233-9be1-05ff934512e3"),
                            Email = "John96@hotmail.com",
                            FirstName = "John",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Boyer",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("ef16750a-64d0-42eb-a865-7e9956f64734"),
                            Email = "Darrell_Lubowitz89@yahoo.com",
                            FirstName = "Darrell",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lubowitz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("791f1929-9e92-44a2-b53e-6941466d5785"),
                            Email = "Cecil_Schroeder95@gmail.com",
                            FirstName = "Cecil",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Schroeder",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("874967d3-9487-41dc-98a4-e5c0594517cf"),
                            Email = "Stella61@hotmail.com",
                            FirstName = "Stella",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "O'Hara",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("be808455-c6e1-4db7-9bc0-561280c3c8c7"),
                            Email = "Patty15@yahoo.com",
                            FirstName = "Patty",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Mills",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a7dae191-56ea-4238-9fba-b86555674f3f"),
                            Email = "Bessie_Nitzsche18@yahoo.com",
                            FirstName = "Bessie",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Nitzsche",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("bc7375ac-65d4-41a4-b471-9b65edd8468f"),
                            Email = "Michelle_Tremblay28@gmail.com",
                            FirstName = "Michelle",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Tremblay",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("13070b57-44ad-43f4-86c0-7db259f7d789"),
                            Email = "Kayla.Adams@yahoo.com",
                            FirstName = "Kayla",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Adams",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("06681a67-f96b-4eb1-9413-9062b2433158"),
                            Email = "Raymond_Carter@hotmail.com",
                            FirstName = "Raymond",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Carter",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("73a01801-39a0-454f-8c97-0c9b5f57bce6"),
                            Email = "Diane_Ritchie@gmail.com",
                            FirstName = "Diane",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Ritchie",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5f65e091-5242-4995-b65a-6c509b72ea2f"),
                            Email = "Christy18@gmail.com",
                            FirstName = "Christy",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lesch",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("a0a3b66a-0324-4d02-8ce4-43171d6891c2"),
                            Email = "Charlie22@yahoo.com",
                            FirstName = "Charlie",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lakin",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("1027f72e-f579-44ee-9e67-c62db2b8f7d0"),
                            Email = "Kirk.Botsford4@yahoo.com",
                            FirstName = "Kirk",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Botsford",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("727b9877-39b4-435b-9aa8-2163682a0a2b"),
                            Email = "Opal54@hotmail.com",
                            FirstName = "Opal",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Willms",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("df535307-015e-44fb-8a9f-9c0411226d60"),
                            Email = "Thomas.Rodriguez@gmail.com",
                            FirstName = "Thomas",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Rodriguez",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("dc9d83f1-98a0-4683-95a8-49c1e46254ae"),
                            Email = "Brian80@yahoo.com",
                            FirstName = "Brian",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Hilll",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("69f70f06-e503-4f77-be38-9007ba8b681a"),
                            Email = "Sonia31@yahoo.com",
                            FirstName = "Sonia",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lubowitz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e9077d8f-a811-497a-a8e1-e82913a7197c"),
                            Email = "Laurence_Ondricka@yahoo.com",
                            FirstName = "Laurence",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Ondricka",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("5481dd7e-a35e-438e-adfc-734349619b83"),
                            Email = "Laverne_Hahn@gmail.com",
                            FirstName = "Laverne",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Hahn",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("e447581f-ac05-4d5d-a871-00e818349d3e"),
                            Email = "Genevieve_Runolfsson78@yahoo.com",
                            FirstName = "Genevieve",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Runolfsson",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("6eefca87-8fc8-44a4-b346-ba71a32f2e64"),
                            Email = "Julia99@hotmail.com",
                            FirstName = "Julia",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Ortiz",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("d480a614-95f5-478d-bb14-7718cd8daf23"),
                            Email = "Fred81@gmail.com",
                            FirstName = "Fred",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Lesch",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("90c37b77-e1ea-46ad-adbf-7acca7ad0015"),
                            Email = "Salvatore_Swaniawski61@yahoo.com",
                            FirstName = "Salvatore",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Swaniawski",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("4d5380f8-0593-4823-b61b-a40b709131ba"),
                            Email = "Patrick_Schroeder@hotmail.com",
                            FirstName = "Patrick",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Schroeder",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("17a82895-0c94-43a5-92c0-69da0170c030"),
                            Email = "Agnes_Shields@yahoo.com",
                            FirstName = "Agnes",
                            IsAdmin = false,
                            IsBlocked = false,
                            LastName = "Shields",
                            PasswordHash = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
